Mayal/urls.py
from django.urls import path, include, re_path
from django.conf import settings
from django.views.static import serve
from .views import *
from .ajax import *
from . import views
from getpaid.registry import registry

urlpatterns = [
    #Para los pagos con criptomoneda.
    path('criptos/',criptos,name="criptos"),
    #Fin de las vistas de pagos con BTC y ETH.

    #Para los pagos de PayPal.
    path('paypal/',paypal,name="paypal"),
    path('paypal-return/', views.PaypalReturnView.as_view(), name='paypal-return'),
    path('paypal-cancel/', views.PaypalCancelView.as_view(), name='paypal-cancel'),
    #Fin de las vistas de pagos con PayPal.

    #Para los pagos con PayU.
    path("order/<int:pk>/", OrderView.as_view(), name="order_detail"),
    path("payments/new/", views.new_payment, name="create-payment"),
    path(
        "success/<uuid:pk>/",
        views.success,
        name="payment-success",
    ),
    path(
        "failure/<uuid:pk>/",
        views.failure,
        name="payment-failure",
    ),
    path(
        "callback/<uuid:pk>/",
        views.callback,
        name="callback",
    ),
    path("", include(registry.urls)),
    #Fin de las vistas de pagos con tarjeta de crédito y débito.

    #Vistas del administrador.
    path('administrador/', index, name="index"),

    path('administrador/listadoCategorias/', ListadosCatSubcat, name='listar_categorias'),
    path('administrador/crearCategoria', CrearCategoria.as_view(), name="crear_categoria"),
    path('administrador/modificarCategoria/<int:pk>', ModificarCategoria.as_view(), name='modificar_categoria'),
    path('administrador/borrarCategoria/<id>',borrarCategoria, name='borrar_categoria'),

    path('administrador/crearSubcategoria', CrearSubcategoria.as_view(), name="crear_subcategoria"),
    path('administrador/modificarSubcategoria/<int:pk>', ModificarSubcategoria.as_view(), name='modificar_subcategoria'),
    path('administrador/borrarSubcategoria/<id>/',borrarSubcategoria, name='borrar_subcategoria'),

    path('administrador/listadoProductos/', ListadoProducto.as_view(), name='listar_productos'),
    path('administrador/crearProducto', CrearProducto.as_view(), name="crear_producto"),
    path('administrador/modificarProducto/<int:pk>', ModificarProducto.as_view(), name='modificar_producto'),
    path('administrador/borrarProducto/<id>',borrarProducto, name='borrar_producto'),
    path('administrador/detalleProducto/<int:pk>/',detalleProducto, name='detalle_producto'),

    path('administrador/agregarImagenes/<int:pk>/',AgregarImagenes, name='agregar_imagenes'),
    path('administrador/guardarImagenes/<int:pk>/',GuardarImagenes, name='guardar_imagenes'),
    path('administrador/borrarImagen/<id>/',borrarImagen, name='borrar_imagen'),

    #url para mostrar mapa de seguimiento
    path('administrador/seguimiento/', seguimiento, name='seguimiento_producto'),  
    path('store/seguimientoEntrega/', tracking, name='seguimiento_entrega'),

    path('store/preguntasFrecuentes/', preguntas, name='faq'),
    path('store/terminosVS/', terminos, name='terminos'),

    # URLs para las funciones AJAX ----------------------------------------------------------------------------------------------
    path('ajax/load_Subcategorias/', load_Subcategorias, name='load_subcategorias'),
    path('ajax/load_Subcategorias_Edit/', load_Subcategorias_Edit, name='load_subcategorias_Edit'),
    path('ajax/simple_chatbot/', chatBot, name='chat'),
    
    # URLs para la TIENDA ----------------------------------------------------------------------------------------------
	path('', store, name="store"),
	path('cart/', cart, name="cart"),
	path('checkout/', checkout, name="checkout"),
	path('update_item/', updateItem, name="update_item"),
	path('process_order/', processOrder, name="process_order"),

    # URLs para LOGIN ----------------------------------------------------------------------------------------------
    path('registro/', registro, name="registro"),

    # URLs para el Usuario ----------------------------------------------------------------------------------------------
    path('administrador/listarUsuario', listarUsuario, name="listarUsuario"),
    path('administrador/editarUsuario/<id>/', editarUsuario, name="editarUsuario"),
    path('administrador/eliminarUsuario/<id>/', eliminarUsuario, name="eliminarUsuario"),
    path('administrador/listarOrdenes', listarOrdenes, name="listarOrdenes"),
    path('administrador/listarOrdenesProductos/<id>/', listarOrdenesProductos, name="listarOrdenesProductos"),
]

# Para mostrar las imagenes guardadas -----------------------------------------------------------------------------------------
urlpatterns += [
    re_path(r'^media/(?P<path>.*)$', serve,{
        'document_root': settings.MEDIA_ROOT,
    })
]

MayalProject/urls.py
from django.contrib import admin
from django.urls import path, include
from Mayal.views import *

from two_factor.urls import urlpatterns as tf_urls
from two_factor.admin import AdminSiteOTPRequired
admin.site.__class__ = AdminSiteOTPRequired

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Mayal.urls')),
    path('', include(tf_urls)),
    path('accounts/', include('django.contrib.auth.urls')),
    path('paypal/',paypal,include('paypal.standard.ipn.urls')),
    path("payments/",include("getpaid.urls")),
    path("payments/",include("getpaid.urls")),
]

Mayal/models.py
from unicodedata import category
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
from django.db import models
from getpaid.abstracts import AbstractOrder

class Order(AbstractOrder):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    date_ordered = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False)
    transaction_id = models.CharField(max_length=100, null=True)
    #buyer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    description = models.CharField(max_length=128, default='Order from mystore')
    total = models.DecimalField(decimal_places=2, max_digits=8, default="199.99")
    currency = models.CharField(max_length=3, default=settings.DEFAULT_CURRENCY)
    ESTADO = (('Activa','Activa'),('Inactiva', 'Inactiva'))
    estado = models.CharField(max_length=10, choices=ESTADO, default="Activa")
    
    def get_user_info(self):
        return {"email": self.user.email}

    def get_total_amount(self):
        return self.total

    def get_description(self):
        return self.description

    def get_currency(self):
        return self.currency

    # either one of those two is required:
    def get_redirect_url(self, *args, success=None, **kwargs):
        # this method will be called to get the url that will be displayed
        # after returning from the paywall page and you can use `success` param
        # to differentiate the behavior in case the backend supports it.
        # By default it returns this:
        return self.get_absolute_url()

    def get_absolute_url(self):
        # This is a standard method recommended in Django documentation.
        # It should return an URL with order details. Here's an example:
        return reverse("order-detail", kwargs={"pk": self.pk})

    # these are optional:
    def is_ready_for_payment(self):
        # Most of the validation will be handled by the form
        # but if you need any extra logic beyond that, you can write it here.
        # This is the default implementation:
        return True

    def get_items(self):
        # Some backends expect you to provide the list of items.
        # This is the default implementation:
        return [{
            "name": self.get_description(),
            "quantity": 1,
            "unit_price": self.get_total_amount(),
        }]

    def __str__(self):
        return str(self.id)

    @property
    def shipping(self):
        shipping = False
        orderitems = self.orderitem_set.all()
        for i in orderitems:
            if i.product.digital == False:
                shipping = True
        return shipping

    @property
    def get_cart_total(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.get_total for item in orderitems])
        return total

    @property
    def get_cart_items(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.quantity for item in orderitems])
        return total

# Create your models here.

# ---CATEGORIA ------------------------------------------------------------------------------------------------------
class Categoria(models.Model):
    id = models.AutoField(primary_key = True)
    nombreCat = models.CharField(max_length = 100)

    def __str__(self):
        return self.nombreCat
#FIN CATEGORIA

# ---SUB-CATEGORIA --------------------------------------------------------------------------------------------------
class Subcategoria(models.Model):
    id = models.AutoField(primary_key = True)
    nombreSub = models.CharField(max_length = 100)
    categoria = models.ForeignKey('Categoria', on_delete = models.CASCADE)

    def __str__(self):
        return self.nombreSub
#FIN SUB-CATEGORIA

# --- PRODUCTO ---------------------------------------------------------------------------------------------------------
class Producto(models.Model):
    id = models.BigAutoField(primary_key=True)
    nombreProd = models.CharField(max_length=250)
    coleccion = models.CharField(max_length=250, null=True, blank=True)
    material = models.CharField(max_length=250, null=True, blank=True)
    color = models.CharField(max_length=250, null=True, blank=True)
    precio = models.DecimalField(max_digits = 5, decimal_places= 2)
    existencias = models.IntegerField(null=True, blank=True)
	
    categoria = models.ForeignKey('Categoria', on_delete = models.SET_NULL, null=True)
    subCategoria = models.ForeignKey('Subcategoria', on_delete = models.SET_NULL, null=True)
    digital = models.BooleanField(default=False,null=True, blank=True)
    imagen = models.ImageField(upload_to='Galeria')

    def __str__(self):
        return self.nombreProd
#FIN PRODUCTO    

# -- IMAGEN -> PRODUCTO ----------------------------------------------------------------------------------------------------
class ImagenProducto(models.Model):
    id = models.AutoField(primary_key = True)
    imagen = models.ImageField(upload_to='Galeria')
    producto = models.ForeignKey('Producto', on_delete = models.CASCADE, related_name='imagenes')


class Customer(models.Model):
	user = models.OneToOneField(User, null=True, blank=True, on_delete=models.CASCADE)
	name = models.CharField(max_length=200, null=True)
	email = models.CharField(max_length=200)

	def __str__(self):
		return self.name

"""class Order(models.Model):
	user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
	date_ordered = models.DateTimeField(auto_now_add=True)
	complete = models.BooleanField(default=False)
	transaction_id = models.CharField(max_length=100, null=True)

	def __str__(self):
		return str(self.id)
		
	@property
	def shipping(self):
		shipping = False
		orderitems = self.orderitem_set.all()
		for i in orderitems:
			if i.product.digital == False:
				shipping = True
		return shipping

	@property
	def get_cart_total(self):
		orderitems = self.orderitem_set.all()
		total = sum([item.get_total for item in orderitems])
		return total 

	@property
	def get_cart_items(self):
		orderitems = self.orderitem_set.all()
		total = sum([item.quantity for item in orderitems])
		return total 
"""

class OrderItem(models.Model):
	product = models.ForeignKey(Producto, on_delete=models.SET_NULL, null=True)
	order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True)
	quantity = models.IntegerField(default=0, null=True, blank=True)
	date_added = models.DateTimeField(auto_now_add=True)

	@property
	def get_total(self):
		total = self.product.precio * self.quantity
		return total

class ShippingAddress(models.Model):
	user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
	order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True)
	address = models.CharField(max_length=200, null=False)
	city = models.CharField(max_length=200, null=False)
	state = models.CharField(max_length=200, null=False)
	zipcode = models.CharField(max_length=200, null=False)
	date_added = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.address

Mayal/forms.py
from django import forms
from django.contrib.admin import widgets
from django.forms import fields
from django.forms.forms import Form
from django.forms.models import ModelMultipleChoiceField
from django.forms.widgets import SelectMultiple
from Mayal.models import *
from django.contrib.admin.widgets import AdminDateWidget
from django.forms.fields import DateField
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class CategoriaForm(forms.ModelForm):
	class Meta:
		model = Categoria
		fields = [
			 'nombreCat'
		]
		labels = {
			'nombreCat': 'Nombre de la Categoría'
		}

class SubcategoriaForm(forms.ModelForm):
	class Meta:
		model = Subcategoria
		fields = [
			 'nombreSub','categoria',
		]
		labels = {
			'nombreSub': 'Nombre de la Subcategoría',
            'categoria': 'Categoría a la que pertenece',
		}

class ProductoForm(forms.ModelForm):
	class Meta:
		model = Producto
		fields = [
			 'nombreProd','coleccion','material','color','precio','existencias','categoria','subCategoria', 'imagen',
		]
		labels = {
			'nombreProd': 'Nombre del Producto',
			'coleccion':'Colección',
			'material':'Material',
			'color':'Color',
			'precio':'Precio',
			'existencias':'Existencias',
            'categoria': 'Categoría',
			'subCategoria':'Subcategoria',
			'imagen': 'Imagen Principal',
		}

class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2',]

        labels = {
            'username': 'Usuario'
        }


class UsuarioForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password', ]


class CustomUserEditForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email',]
        exclude = ['password']

        labels = {
            'username': 'Usuario'
        }

Mayal/templates/CRUDs/Producto/agregarImagenes.html
{% extends 'administrador/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}<title>Registrar Producto</title>{% endblock title%}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg-7">
            <div class="card shadow-lg border-0 rounded-lg mt-5">
                <div class="card-header"><h3 class="text-center font-weight-light my-4">Agregar Imagenes a: {{ producto }}</h3>
                    <div align="center"><img src=" {{ producto.imagen.url }}" width="300" height="auto"/></div>
                </div>

                <div class="card-body">
                    <form method="post" role="form" action=" {% url 'guardar_imagenes' producto.pk %}" enctype="multipart/form-data">
                        {% csrf_token %}
                        
                        <div class="form-group m-3" align="center">
                            <label>Seleccionar más Imagenes para subir</label>
                            <br><br>
                            <input required name="imagenes" type="file" multiple class="form-control-file">
                        </div>

                        <div class="mt-4 mb-0" align="center">
                            <a class="btn btn-danger" href="{% url 'listar_productos' %}"><i class="fa fa-arrow-left"
                                aria-hidden="true"></i> Regresar</a>
                            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                            <button type="submit" class="btn btn-success float-right"><i class="fa fa-check"
                                aria-hidden="true"></i> Guardar</button>

                            {% comment %} <div class="d-grid"><input type="submit" value="Finalizar" class="btn btn-primary btn-block"></div> {% endcomment %}
                        </div>
                    </form>
                    <br>
                    <div class="row" align="center">
                        {% for ip in imagenesProducto %}
                           
                                <div class="card">
                                    <div class="card-body"   align="center">
                                        <img src=" {{ ip.imagen.url }}"  width="300" height="auto"  align="center"/>
                                    </div>
                                    <div class="card-footer" align="center">
                                        <a class="btn btn-danger" href="#" onclick="eliminarImagenProducto({{ ip.id }})"><i class="fa fa-trash" aria-hidden="true" style="font-size:24px;color:rgb(255, 255, 255);text-shadow:2px 2px 4px #000000;"></i></a>
                                    </div>
                                </div>
                       
                        {% endfor %}
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>

    
{% endblock content %}

{% block js %}
    <script>
        function eliminarImagenProducto(id){
            Swal.fire({
                title: 'Estas seguro?',
                showCancelButton: true,
                confirmButtonText: 'Si, Eliminar',
                confirmButtonColor: '#FF0000',
                cancelButtonText: 'No, Cancelar',
                reverseButtons: true,

            }).then(function(result) {
                if (result.isConfirmed) {
                    window.location.href = "/administrador/borrarImagen/"+id
                }
            })
        }
    </script>
{% endblock js%}

Mayal/templates/CRUDs/Producto/crear.html
{% extends 'administrador/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}<title>Registrar Producto</title>{% endblock title%}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg-7">
            <div class="card shadow-lg border-0 rounded-lg mt-5">
                <div class="card-header"><h3 class="text-center font-weight-light my-4">Nuevo Producto</h3></div>
                <div class="card-body">
                    <form method="post" role="form" action="" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-floating mb-3">
                            {{form.nombreProd|as_crispy_field}}
                        </div>
                        <div class="form-floating mb-3">
                            {{form.coleccion|as_crispy_field}}
                        </div>
                        <div class="form-floating mb-3">
                            {{form.material|as_crispy_field}}
                        </div>
                        <div class="form-floating mb-3">
                            {{form.color|as_crispy_field}}
                        </div>
                        <div class="form-floating mb-3">
                            {{form.precio|as_crispy_field}}
                        </div>
                        <div class="form-floating mb-3">
                            {{form.existencias|as_crispy_field}}
                        </div>

                        <div class="form-floating mb-3">
                            {{form.categoria|as_crispy_field}}
                        </div>
                        <div class="form-floating mb-3">
                            {{form.subCategoria|as_crispy_field}}
                        </div>

                        <div class="form-floating mb-3">
                            {{form.imagen|as_crispy_field}}
                        </div>

                        <div class="mt-4 mb-0">
                            <div class="d-grid"><input type="submit" value="Finalizar" class="btn btn-primary btn-block"></div>
                        </div>
                    </form>
                </div>
                <div class="card-footer text-center py-3">
                    <div class="small"></div>
                </div>
            </div>
        </div>
    </div>
</div>



<script type="text/javascript">

    window.onload = VaciarSelects(); // Al cargar la página, que el select de Subcategoria esté vacío

// SELECT DEPENDIENTE PARA LAS SUBCATEGORIAS====================================
    $(document).ready(function(){
        $("#id_categoria").on("change", getSubcategorias);    
    });

    function getSubcategorias(){
        var categoriaId = $("#id_categoria").val();
        if (categoriaId){
            $("#id_subCategoria").html("");
            var request = $.ajax({
                type: "GET",
                url: "{% url 'load_subcategorias' %}",
                data: {
                    "catId":categoriaId
                },
            });
            request.done(function(response){
                $("#id_subCategoria").html(response);
               
            });
    
        }else{
            $("#id_subCategoria").html('<option value="" selected = "selected">-----------</option>');      
            $("#id_subCategoria").trigger("change");
        }
    }
//===========================================================================

// ===========================================================================
    function VaciarSelects(){
        $("#id_subCategoria").html('<option value="" selected = "selected">-----------</option>');
    }
//==================================================================================

</script>
 
{% endblock content %}

Mayal/templates/CRUDs/Producto/detalle.html
{% extends 'administrador/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}<title>Detalle Producto</title>{% endblock title%}

{% block content %}
<div class="container">
    <div class="row justify-content-center" width="300">
        <div class="col-lg-9">
            <div class="card shadow-lg border-0 rounded-lg mt-5">
                <div class="card-header"><h3 class="text-center font-weight-light my-4">Información del producto: {{ producto }}</h3>
                    <table>
                        <tr>
                            <td width="350">
                                <div align="center">
                                    <img src=" {{ producto.imagen.url }}" width="250" height="auto"/>
                                    <label><b>Imágen principal del producto</b></label>
                                </div>
                            </td>
                            <td width="400">
                                <label><b>Nombre: </b> {{producto.nombreProd}}</label><br><br>

                                <label><b>Categoría: </b> {{producto.categoria}}</label><br>
                                <label><b>Subcategoría: </b> {{producto.subCategoria}}</label><br>
                                <label><b>Precio: </b> ${{producto.precio}}</label><br><br>

                                <label><b>Coleccion: </b>  {% if producto.coleccion != None %}  {{producto.coleccion}} {% else %}   -- {% endif %}</label><br>
                                <label><b>Material: </b> {% if producto.material != None %}  {{producto.material}} {% else %}    -- {% endif %}</label><br>
                                <label><b>Existencias: </b> {% if producto.existencias != None %} {{producto.existencias}} {% else %}   -- {% endif %}</label><br>
                                
                            </td>
                            <td align="center">
                                <a class="btn btn-danger" href="{% url 'listar_productos' %}"><i class="fa fa-arrow-left" aria-hidden="true"></i> Regresar</a><br><br>

                                <a class="btn btn-primary" href="{% url 'agregar_imagenes' producto.id %}" style="size:5px"><i class="fa fa-plus" aria-hidden="true"></i> Imágenes</a><br><br>
                                    
                                <a class="btn btn-warning" href="{% url 'modificar_producto' producto.id %}"><i class="fa fa-pencil fa-2x" aria-hidden="true" style="font-size:22px;color:rgb(255, 255, 255);text-shadow:2px 2px 4px #000000;"></i>  Editar</a>
                            </td>
                            
                        </tr>
                    </table>
                </div>

                <div class="card-body">
                    <div class="row" align="center">
                        <label><b>Imagenes asociadas a éste producto</b></label><br><br>
                        {% if imagenesProducto %}
                            {% for ip in imagenesProducto %}
                                <div class="col-lg-4" >
                                    <img class="thumbnail" width="300" height="auto"  align="center" src="{{ip.imagen.url}}">
                                </div>
                            {% endfor %}
                        {% else %}
                            <label>Aún no hay Imagenes asociadas a éste producto</label><br><br>
                        {% endif %}
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

Mayal/templates/CRUDs/Producto/editar.html
{% extends 'administrador/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}<title>Editar Producto</title>{% endblock title%}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg-7">
            <div class="card shadow-lg border-0 rounded-lg mt-5">
                <div class="card-header"><h3 class="text-center font-weight-light my-4">Editar Producto: {{producto}}</h3></div>
                <div class="card-body">
                    <form method="post" role="form" action="" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-floating mb-3">
                            {{form.nombreProd|as_crispy_field}}
                        </div>
                        <div class="form-floating mb-3">
                            {{form.coleccion|as_crispy_field}}
                        </div>
                        <div class="form-floating mb-3">
                            {{form.material|as_crispy_field}}
                        </div>
                        <div class="form-floating mb-3">
                            {{form.color|as_crispy_field}}
                        </div>
                        <div class="form-floating mb-3">
                            {{form.precio|as_crispy_field}}
                        </div>
                        <div class="form-floating mb-3">
                            {{form.existencias|as_crispy_field}}
                        </div>

                        <div class="form-floating mb-3">
                            {{form.categoria|as_crispy_field}}
                        </div>
                        <div class="form-floating mb-3">
                            {{form.subCategoria|as_crispy_field}}
                        </div>

                        <div class="form-floating mb-3">
                            {{form.imagen|as_crispy_field}}
                        </div>

                        <div class="form-floating mb-3" align="center">
                            <img src=" {{ producto.imagen.url }}" width="300" height="auto"/>
                            <h6> Imágen Actual </h6>
                        </div>


                        <div class="mt-4 mb-0" align="center">
                            {% comment %} <div class="d-grid"><input type="submit" value="Finalizar" class="btn btn-primary btn-block"></div> {% endcomment %}
                            <a class="btn btn-danger" href="{% url 'listar_productos' %}"><i class="fa fa-arrow-left"
                                aria-hidden="true"></i> Regresar</a>
                            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                            <button type="submit" class="btn btn-success float-right"><i class="fa fa-check"
                                aria-hidden="true"></i> Guardar</button>
                        </div>
                    </form>
                </div>
                <div class="card-footer text-center py-3">
                    <div class="small"></div>
                </div>
            </div>
        </div>
    </div>
</div>



<script type="text/javascript">

    window.onload = getSubcategoriasEdit(); // Al cargar la página, que el select de Subcategoria esté vacío

// SELECT DEPENDIENTE PARA LAS SUBCATEGORIAS====================================
    $(document).ready(function(){
        $("#id_categoria").on("change", getSubcategorias);    
    });

    function getSubcategorias(){
        var categoriaId = $("#id_categoria").val();
        if (categoriaId){
            $("#id_subCategoria").html("");
            var request = $.ajax({
                type: "GET",
                url: "{% url 'load_subcategorias' %}",
                data: {
                    "catId":categoriaId,
                },
            });
            request.done(function(response){
                $("#id_subCategoria").html(response);
               
            });
    
        }
    }
//===========================================================================

    function getSubcategoriasEdit(){
        var categoriaId = $("#id_categoria").val();
        var productoId = {{producto.pk}};
        if (categoriaId){
            $("#id_subCategoria").html("");
            var request = $.ajax({
                type: "GET",
                url: "{% url 'load_subcategorias_Edit' %}",
                data: {
                    "catId":categoriaId,
                    "prodId":productoId,
                },
            });
            request.done(function(response){
                $("#id_subCategoria").html(response);
            
            });

        }
    }
</script>
 
{% endblock content %}